# -*- coding: utf-8 -*-
"""FinalDopamine_III.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QFWq_-IEoSCiv-QoIg-j4Oz6cic5sTml
"""

#You should delete the save files to run a new simulation. 
#If this is not done this script will load the previous checkpoints and logs.

#!pip install -U dopamine-rl

import numpy as np
import os
#from dopamine.agents.dqn import dqn_agent

from dopamine.discrete_domains import run_experiment
from dopamine.colab import utils as colab_utils
from absl import flags
import gin.tf

from google.colab import drive 
drive.mount('/content/drive')

path = '/content/drive/My Drive/SaveFiles/Data/Dopamine/'
LOG_PATH = os.path.join(path, 'dqn')

import sys
sys.path.append(path)
from dqn_agent_new import *

def create_random_dqn_agent(sess, environment, summary_writer=None):
  """The Runner class will expect a function of this type to create an agent."""
  print('sess',sess)
  return JaxxDQNAgent(sess, num_actions=environment.action_space.n)

gin.parse_config_file('/content/drive/My Drive/SaveFiles/Data/Dopamine/dqn_cartpol_MODI.gin')
random_dqn_runner = run_experiment.TrainRunner(LOG_PATH, create_random_dqn_agent)

print('Will train agent, please be patient, may be a while...')
random_dqn_runner.run_experiment()
print('Done training!')

data = colab_utils.read_experiment(LOG_PATH, verbose=True, summary_keys=['train_episode_returns'])
data['agent'] = 'DQN'
data['run'] = 1

import seaborn as sns
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(16,8))
sns.lineplot(x='iteration', y='train_episode_returns', hue='agent',
             data=data, ax=ax)
plt.title('Cartpole')
plt.show()